version: "3.5"

services:
  api:
    build: .
    links:
      - "db"
    ports:
      - 8080:8080
    networks:
      - backend
  db:
    image: mongo:3.6
    ports:
      - 27018:27017
    networks:
      - backend

networks:
  backend: